#!/usr/bin/python3

'''Automatically opens user inputted site into web browser.
'''
import webbrowser
from urllib.parse import quote

__author__ = 'Brandon Phillips'
__date__ = '12/30/2018'
__version__ = '1.0'

def run():
	domain_ext = ['.com','.ca','.org','.net','edu','.gov','.us'] #Set accepted domain extensuions.
	url = '' #Initialize url as empty string. 

	print('What would you like to search?')
	search = input('>> ')

	for d in domain_ext: 
		if search.endswith(d) and len(search) > len(d): #Check if user included a valid domain extension.
			if search.startswith('https://'): #Check for inclusion of https scheme.
				url = search 
			else: #Else; assume url is missing the https scheme.
				url = 'https://' + search 
			break 

	if url == '': #If url is not a valid, assume that user wants to search instead.
		url = 'https://duckduckgo.com/?q={}'.format(quote(search)) #Make search url-friendly.
	
	webbrowser.open(url) 
	print('Done!')

if __name__ == '__main__':
	run()
	
